name: Generate & Deploy Content

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'scripts/generate_content.py' # Only run if the script changes
  workflow_dispatch: # Allows manual trigger from GitHub UI
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (e.g., '0 0 * * *' for daily at midnight UTC)

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to write to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use v4 for better performance and security

      - name: Set up Python
        uses: actions/setup-python@v5 # Use v5 for better performance and security
        with:
          python-version: '3.9' # Specify a Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Install the requests library for API calls
          # If you were using the actual google-generativeai library, uncomment this:
          # pip install google-generativeai

      - name: Generate content
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }} # Access the API key from GitHub Secrets
          # If using Gemini, you'd also have: GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/generate_content.py # Run your Python script

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update content via script"
          file_pattern: 'updates.json' # Only commit this file
          branch: main # Specify the branch to push to
          skip_fetch: true # Speeds up the action by skipping fetching
