name: Generate & Deploy Content

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

# Add permissions for the GITHUB_TOKEN to write to the repository
permissions:
  contents: write # This grants write access to the repository contents

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # Install the requests library

    - name: Generate content
      run: python scripts/generate_content.py
      env:
        # This is CRUCIAL: The name here must EXACTLY match your GitHub Secret name
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }} 

    - name: Commit and Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add updates.json
        git commit -m "Update content data" || echo "No changes to commit" # Only commit if there are changes
        git push
